### ISSUE TITLE
ReaPack compatibility?

### ISSUE THREAD

**Issue by daxliniere** [Buy-One/REAPER-scripts#1]
Hey BuyOne, will you be adding ReaPack compatibility?

**Comment by Buy-One** [comment]
@daxliniere

I don't think so. Learning how to create a repo index is too much of a hassle for me and i've seen people run into problems.
I was thinking of writing my own installer script but can't tell when or if i'll do it.
For now something to be aware of is that several scripts are marked as META in the name. This is how they started out when i was adding scripts directly to ReaPack which has a mechanism of handling these. ReaPack would install them as individual scripts under different names listed in the META script header because its functionality depends on the name. They're still in ReaPack, so if their version in my repo isn't different from the one available in ReaPack, they can be installed from there, otherwise one would need to manually duplicate the file marked as META and rename each copy with the names listed inside.

**Comment by daxliniere** [comment]
It's a shame, since the search function of ReaScript is one of the best parts. When I need a script, I'll usually start by searching through ReaPack and often enough there is something in there.

**Comment by Buy-One** [comment]
I completely agree that ReaPack is very convenient. But at the very outside if you care about updates to my repo you're welcome to subscribe to it and receive an email whenever there's a new version or a new script.

**Comment by daxliniere** [comment]
It's not so much about staying updated, it's that I don't know what is in your repo, nor would I know if I were searching for a script.

**Comment by daxliniere** [comment]
You also have so many script that it would take an age to install them all.

**Comment by Buy-One** [comment]
Regarding installation that's true. I just posted a feature request to allow importing scripts and folders with scripts via drag & drop.

As far as knowing what's in here, i maintain [a list of them](https://github.com/Buy-One/REAPER-scripts/wiki/SCRIPT-LIST)
Staying updated can be helpful if the name of an updated/new script piques your interest as something you may find potentially useful and want to have.

But yeah, one-stop shop approach is unbeatable.

**Comment by daxliniere** [comment]
Funnily enough, I managed to get them all installed in a few minutes. Though folders aren't recursed, at least you can CTRL+A every script in a folder and import that way.

Not to keep pestering you about it (I promise this will be the last time), but is it because you don't want to spend the time setting up your repo for ReaPack compatibility? If so, perhaps I could take care of that for you to save you the time and help others out?

**Comment by Buy-One** [comment]
> is it because you don't want to spend the time setting up your repo for ReaPack compatibility

Yeah. But doing this in my repo instead of myself you'd need full access, wouldn't you?

**Comment by daxliniere** [comment]
As far as I know, ReaPack compatibility just requires an appropriately formatted index file.
But I will look it up and learn how to do it.

**Comment by Buy-One** [comment]
I've just had another look. 
https://github.com/cfillion/reapack-index/wiki

Auto-generation of the index file requires local Git installation, which i won't do. 

Alternatively a repo template can be used
https://forum.cockos.com/showpost.php?p=2386966&postcount=6
https://github.com/cfillion/reapack-repository-template/tree/master

which i just tried and all Git workflows failed.

Or the index file can be coded by hand, which means too much error prone work, so the stars didn't align.  ¯\_(ツ)_/¯

**Comment by daxliniere** [comment]
No worries, thanks for looking into it! :)
