### ISSUE TITLE
Is it possible to create a script that activates and deactivates ReaXcomp's "Current band only" button?

### ISSUE THREAD

**Issue by Lo-lo78** [Buy-One/REAPER-scripts#7]
@Buy-One 
I was trying with gpt chat but I didn't get to the solution.
Unfortunately I'm not a developer.
Is it possible to create this script to facilitate keyboard use with ReaXcomp?
I don't use a mouse!
Thanks for everything you do!

**Comment by Buy-One** [comment]
Strangely enough the solo band checkbox cannot be accessed via the API. Other bands can be disabled instead but i believe this is not the same as soloing it because even when a band is soloed there's still interaction with neighboring enabled bands, which affects the behavior of the soloed band. 

If you feel like it you could submit a feature request for making other ReaXComp parameters exposed to the API and automation (because these are linked), among those "Solo current band" checkbox.
